#!/bin/bash

# 便利スクリプトのファイルはプロジェクト直下に置く
# PhpStormのFile Watcherによるファイル反映がリアルタイムになるため便利になる。

# localのループバックIPを一つ設定する
#LOCAL_IP=$(grep LOCAL_IP .env | cut -d '=' -f2)
# macにて必要に応じて sudo ifconfig lo0 alias を叩く
#if [[ "$OSTYPE" == "darwin"* ]] && ! ifconfig | grep -i "$LOCAL_IP" > /dev/null; then
#    echo "${LOCAL_IP}が無効なのでエイリアスを生成します。パスワードを入力してください。"
#    sudo ifconfig lo0 alias "$LOCAL_IP" up
#fi

case "$1" in

"phpstan-on-save")
    # PHPStormのFile Watchers機能を見越したコマンド
    docker compose -f ./docker/mac/docker-compose.yml exec app composer ide-helper
    echo "${@:2}" | sed -e 's/src/./' | xargs -r docker compose -f ./docker/mac/docker-compose.yml exec app composer phpstan
    ;;

"php-cs-fixer")
    # PHPStormのFile Watchers機能を見越したコマンド
    echo "${@:2}" | sed -e 's/src/./' | xargs -r docker compose -f ./docker/mac/docker-compose.yml exec app composer php-cs-fixer
    ;;
esac
