FROM alpine:latest

ENV DRIVER_URL https://jdbc.postgresql.org/download/postgresql-42.2.20.jar
ENV APP_URL https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar

# JDK8のインストール
RUN apk add openjdk8

WORKDIR /app

# schemaspyのインストール
RUN apk --update add graphviz ttf-dejavu && \
    apk --update add --virtual .builddep tzdata wget && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    wget -O postgresql-connector-java.jar ${DRIVER_URL} && \
    wget -O schemaspy.jar ${APP_URL} && \
    apk del .builddep && \
    rm -rf /var/cache/apk/*
